### ISSUE TITLE
JSONDoc crashes on @OneToOne annotations

### ISSUE THREAD

**Issue by tairv** [fabiomaffioletti/jsondoc#156]
GIVEN
Using spring boot for exposing RESTful service and using JSONDoc for documenting.
I have **user.java** with
```
...
@ApiObjectField(description = "User's contacts list")
@OneToOne(mappedBy = "user")
private ContactsList contactsList;
...
```

And **ContactsList.java**
```
...
@JsonIgnore
@OneToOne
private User user;
...
```

It all works when I make a GET request to see User for example.

WHEN
Going to localhost:8080/jsondoc it throws an error.

THEN
```
java.lang.StackOverflowError: null
	at sun.reflect.generics.parser.SignatureParser.parseTypeArgument(SignatureParser.java:415)
	at sun.reflect.generics.parser.SignatureParser.parseTypeArguments(SignatureParser.java:396)
	at sun.reflect.generics.parser.SignatureParser.parsePackageNameAndSimpleClassTypeSignature(SignatureParser.java:346)
	at sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature(SignatureParser.java:310)
	at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:289)
	at sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:283)
	at sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:485)
	at sun.reflect.generics.parser.SignatureParser.parseTypeSig(SignatureParser.java:188)
	at sun.reflect.generics.repository.FieldRepository.parse(FieldRepository.java:52)
	at sun.reflect.generics.repository.FieldRepository.parse(FieldRepository.java:42)
	at sun.reflect.generics.repository.AbstractRepository.<init>(AbstractRepository.java:74)
	at sun.reflect.generics.repository.FieldRepository.<init>(FieldRepository.java:48)
	at sun.reflect.generics.repository.FieldRepository.make(FieldRepository.java:66)
	at java.lang.reflect.Field.getGenericInfo(Field.java:105)
	at java.lang.reflect.Field.getGenericType(Field.java:247)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.build(JSONDocTemplateBuilder.java:57)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.getValue(JSONDocTemplateBuilder.java:92)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.build(JSONDocTemplateBuilder.java:57)
	... (x100)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.build(JSONDocTemplateBuilder.java:57)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.getValue(JSONDocTemplateBuilder.java:92)
```

@ManyToMany and @OneToMany does not cause any problems.

Thank you in advance

**Comment by fabiomaffioletti** [comment]
It's not the @OneToOne annotation, read the `processtemplate` docs here: http://jsondoc.org/annotations.html#apiobjectfield

**Comment by tairv** [comment]
Thank you for reply.

It is written there that "Set this to **true** to avoid StackOverflow..." but it fixed the problem when I set it to **false**. Am I misunderstanding something?

**Comment by fabiomaffioletti** [comment]
It's a mistake on the annotation documentation. Sorry about that!
