### ISSUE TITLE
Gernerics Related to Bug #146 and #174

### ISSUE THREAD

**Issue by Valdur5** [fabiomaffioletti/jsondoc#235]
Hello,

thanks for providing such a cool documentation framework it works well but one really big thing is still broken, different people described the same problem in Issue 146 and 174.

I want to return a generic List because I don't want to build for every object a wrapper object just for some HATEOAS extra fields. Thats why I want to return a generic Array like this:

public @ApiResponseObject()
	ItemCollection<Mountain> getAllMountains() {

I am using JSONdoc 1.2.17 

And here is the dump (part of)

java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to java.lang.reflect.ParameterizedType
	at org.jsondoc.springmvc.scanner.AbstractSpringJSONDocScanner.buildJSONDocObjectsCandidates(AbstractSpringJSONDocScanner.java:112) ~[jsondoc-springmvc-1.2.17.jar:na]
	at org.jsondoc.springmvc.scanner.AbstractSpringJSONDocScanner.appendSubCandidates(AbstractSpringJSONDocScanner.java:168) ~[jsondoc-springmvc-1.2.17.jar:na]
	at org.jsondoc.springmvc.scanner.AbstractSpringJSONDocScanner.jsondocObjects(AbstractSpringJSONDocScanner.java:200) ~[jsondoc-springmvc-1.2.17.jar:na]
	at org.jsondoc.core.scanner.AbstractJSONDocScanner.getJSONDoc(AbstractJSONDocScanner.java:96) ~[jsondoc-core-1.2.17.jar:na]
	at org.jsondoc.springmvc.controller.JSONDocController.getApi(JSONDocController.java:70) ~[jsondoc-springmvc-1.2.17.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]

**Comment by maxmumford** [comment]
Can confirm this bug still exists at 1.2.17. I can't use this (great looking) lib until it's fixed, so I'm off to find something else unfortunately ..

**Comment by ST-DDT** [comment]
Duplicate of https://github.com/fabiomaffioletti/jsondoc/issues/226 (A fix is described there too)
