### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by Reya** [fabiomaffioletti/jsondoc#95]
GIVEN
```
@ApiObject(name = "User", description = "A user object")
public class Utilisateur implements java.io.Serializable
{
    @ApiObjectField( description = "The user id")
    private Long id;
    @ApiObjectField( description = "The user firstname")
    private String firstname;
    @ApiObjectField( description = "The user's default group")
    private Groupe defaultgroup;
}
```
```
@ApiObject(name = "Group", description = "A group object")
public class Groupe implements java.io.Serializable
{
    @ApiObjectField(name = "id", description = "The group identifier")
    private Long id;
    @ApiObjectField( description = "The group name")
    private String name;
    @ApiObjectField(name = "owner", description = "The group owner", required = true)
    private Utilisateur owner;
}
```
WHEN

Nothing

THEN
```
19-Feb-2015 14:06:25.710 SEVERE [http-apr-8084-exec-121] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [dispatcher] in context with path [/] threw exception [Handler processing failed; nested exception is java.lang.StackOverflowError] with root cause
 java.lang.StackOverflowError
	at java.lang.Class.getClassLoader(Class.java:669)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:306)
	at sun.reflect.annotation.AnnotationParser$1.run(AnnotationParser.java:303)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.annotation.AnnotationParser.annotationForMap(AnnotationParser.java:303)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:293)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1140)
	at java.lang.reflect.Field.getAnnotation(Field.java:1114)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:190)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.getAllDeclaredFields(JSONDocTemplateBuilder.java:73)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.build(JSONDocTemplateBuilder.java:30)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.getValue(JSONDocTemplateBuilder.java:65)
	at org.jsondoc.core.util.JSONDocTemplateBuilder.build(JSONDocTemplateBuilder.java:33)
        ...
```

It would be nice if we can define a field as the identify of the class (like Jackson does with @JsonIdentityInfo):
```
"group":{
  "owner": {   //return just the field "id" and not the other
    "id": 0
  },
  "id": 1,
  "name": "Administrator"
}
```
```
"user": {   
    "id": 0,
    "firstname": "nicolas"
    "defaultgroup":{      //return just the field "id" and not the other
	    "id": 1
    }
}
```

**Comment by fabiomaffioletti** [comment]
added a processtemplate attribute to ApiObjectField annotation. Defaults to true. If set to false then the field class is not inspected and a generic Object template is used to build the field template.
